### ISSUE TITLE
Error in determining the right morningnumber and eveningnumber

### ISSUE THREAD

**Issue by Wim3d** [SensorsIot/HowIsMyDay#3]
Great sketch for me to learn to handle JSON objects! When I tried it, I found out that the determination of the morningnumber and the eveningnumber was not correct.
When I changed 
      if (timeUTC[i] > morningHour && timeUTC[i] <= morningHour + 3) morningNumber = i;
      if (timeUTC[i] > eveningHour && timeUTC[i] <= eveningHour + 3) eveningNumber = i;
to
      if (timeUTC[i] >= morningHour && timeUTC[i] < morningHour + 3) morningNumber = i;
      if (timeUTC[i] >= eveningHour && timeUTC[i] < eveningHour + 3) eveningNumber = i;
It works correct

**Comment by SensorsIot** [comment]
Changed. Thanks!
